# Generated by Django 5.2 on 2026-04-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee1',
            fields=[
                ('EmpId', models.IntegerField(primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=20)),
                ('Salary', models.IntegerField()),
                ('Edit', models.CharField(max_length=10)),
                ('Delete', models.CharField(max_length=10)),
            ],
        ),
    ]
