# Generated by Django 5.2 on 2026-04-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Eid', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=20)),
                ('Phno', models.CharField(max_length=15)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
